export const ADD_CHOCOLATE = "ADD_CHOCOLATE";
export const REMOVE_CHOCOLATE = "REMOVE_CHOCOLATE";
export const GET_CHOCOLATE = "GET_CHOCOLATE";

export const UPDATE_CUSTOM_ITEMS = "UPDATE_CUSTOM_ITEMS";

export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
